[package]
name = "dbutil_2_3-Exploit"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"

[dependencies.windows-sys]
version = "0.52"
features = [
    "Data_Xml_Dom",
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Ioctl",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]

